### PR TITLE
update documents

### PR DESCRIPTION
**Pull request by guoqing-noaa**

### CODE REVIEW

**Comment by guoqing-noaa** [comment]
Hi all, if you have time, please take a look at the updated build_and_run.md:
https://github.com/guoqing-noaa/rrfs-workflow/blob/doc/docs/build_and_run.md

Let me know if there is anything not clear. Thanks!

**Comment by EricJames-NOAA** [comment]
@guoqing-noaa I have been working through it in the background today!  I will let you know if I find any issues.

**Comment by guoqing-noaa** [comment]
Thanks, @EricJames-NOAA

**Comment by EricJames-NOAA** [comment]
> Thanks, @EricJames-NOAA

@guoqing-noaa I'm having trouble with this step:

./setup_exp.py exp/exp_setup

In the previous step, we copied exp_setup to the workflow/ directory, so shouldn't it be:

./setup_exp.py exp_setup

But I can't get that to work either:

[Eric.James@fe7 workflow]$ ./setup_exp.py exp_setup
Traceback (most recent call last):
  File "./setup_exp.py", line 20, in <module>
    source(fpath)
  File "/mnt/lfs4/BMC/wrfruc/ejames/coding/rrfs-workflow/workflow/xml_funcs/base.py", line 22, in source
    raise Exception(f"Error sourcing bash file: {stderr}")
Exception: Error sourcing bash file: bash: exp_setup: No such file or directory

Maybe something is missing in my environment.

**Comment by guoqing-noaa** [comment]
Thanks, @EricJames-NOAA 
This is to correct outdated information in the repo, such as `./setup_exp.py exp/exp_setup` you mentioned.

It should be ./setup_exp.py exp.setup. Sorry about that.

**Comment by guoqing-noaa** [comment]
@EricJames-NOAA , could you follow my updated instructions here:
https://github.com/guoqing-noaa/rrfs-workflow/blob/doc/docs/build_and_run.md

Thanks!

**Comment by guoqing-noaa** [comment]
@EricJames-NOAA I think I inherited the typo even in my updated instructions. I just corrected it.

Thanks a lot for testing. It looks like specifying `exp.setup` should be optional so as to improve user experiences.
I will create a PR to make this happen.

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA I think I inherited the typo even in my updated instructions. I just corrected it.
> 
> Thanks a lot for testing. It looks like specifying `exp.setup` should be optional so as to improve user experiences. I will create a PR to make this happen.

@guoqing-noaa thanks!  It seems to be working now!  I am able to submit the XML and get jobs in the queue.  

I'll try to get to the UPP step so I can easily test UPP modifications

**Comment by guoqing-noaa** [comment]
Great. Thanks, @EricJames-NOAA 
Do you test on Hera or Jet?

**Comment by EricJames-NOAA** [comment]
> Great. Thanks, @EricJames-NOAA Do you test on Hera or Jet?

@guoqing-noaa on Jet.

**Comment by guoqing-noaa** [comment]
OK, now users can run `setup_exp.py` without the need to specify a command line option.

**Pull request merged**
